apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/project-4cfdac74-a7d9-4d41-abf/sofe3980u/binarycalculator:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  type: LoadBalancer
  selector:
    app: binarycalculator
  ports:
    - port: 8080
      targetPort: 8080